//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAP_WCF.ProxyServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://schemas.datacontract.org/2004/07/Proxy_WCF")]
    [System.SerializableAttribute()]
    public partial class Contract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] citiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commercial_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string country_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] cities {
            get {
                return this.citiesField;
            }
            set {
                if ((object.ReferenceEquals(this.citiesField, value) != true)) {
                    this.citiesField = value;
                    this.RaisePropertyChanged("cities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string commercial_name {
            get {
                return this.commercial_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.commercial_nameField, value) != true)) {
                    this.commercial_nameField = value;
                    this.RaisePropertyChanged("commercial_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string country_code {
            get {
                return this.country_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.country_codeField, value) != true)) {
                    this.country_codeField = value;
                    this.RaisePropertyChanged("country_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/Proxy_WCF")]
    [System.SerializableAttribute()]
    public partial class Station : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int available_bike_standsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int available_bikesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bankingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bike_standsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bonusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contract_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long last_updateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAP_WCF.ProxyServices.Position positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int available_bike_stands {
            get {
                return this.available_bike_standsField;
            }
            set {
                if ((this.available_bike_standsField.Equals(value) != true)) {
                    this.available_bike_standsField = value;
                    this.RaisePropertyChanged("available_bike_stands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int available_bikes {
            get {
                return this.available_bikesField;
            }
            set {
                if ((this.available_bikesField.Equals(value) != true)) {
                    this.available_bikesField = value;
                    this.RaisePropertyChanged("available_bikes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool banking {
            get {
                return this.bankingField;
            }
            set {
                if ((this.bankingField.Equals(value) != true)) {
                    this.bankingField = value;
                    this.RaisePropertyChanged("banking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bike_stands {
            get {
                return this.bike_standsField;
            }
            set {
                if ((this.bike_standsField.Equals(value) != true)) {
                    this.bike_standsField = value;
                    this.RaisePropertyChanged("bike_stands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bonus {
            get {
                return this.bonusField;
            }
            set {
                if ((this.bonusField.Equals(value) != true)) {
                    this.bonusField = value;
                    this.RaisePropertyChanged("bonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contract_name {
            get {
                return this.contract_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.contract_nameField, value) != true)) {
                    this.contract_nameField = value;
                    this.RaisePropertyChanged("contract_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAP_WCF.ProxyServices.Position position {
            get {
                return this.positionField;
            }
            set {
                if ((object.ReferenceEquals(this.positionField, value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/Proxy_WCF")]
    [System.SerializableAttribute()]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float latField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float lngField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float lat {
            get {
                return this.latField;
            }
            set {
                if ((this.latField.Equals(value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float lng {
            get {
                return this.lngField;
            }
            set {
                if ((this.lngField.Equals(value) != true)) {
                    this.lngField = value;
                    this.RaisePropertyChanged("lng");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Place", Namespace="http://schemas.datacontract.org/2004/07/Proxy_WCF")]
    [System.SerializableAttribute()]
    public partial class Place : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] boundingboxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string display_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double importanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string latField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string licenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long osm_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string osm_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long place_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long place_rankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] boundingbox {
            get {
                return this.boundingboxField;
            }
            set {
                if ((object.ReferenceEquals(this.boundingboxField, value) != true)) {
                    this.boundingboxField = value;
                    this.RaisePropertyChanged("boundingbox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string display_name {
            get {
                return this.display_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.display_nameField, value) != true)) {
                    this.display_nameField = value;
                    this.RaisePropertyChanged("display_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string icon {
            get {
                return this.iconField;
            }
            set {
                if ((object.ReferenceEquals(this.iconField, value) != true)) {
                    this.iconField = value;
                    this.RaisePropertyChanged("icon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double importance {
            get {
                return this.importanceField;
            }
            set {
                if ((this.importanceField.Equals(value) != true)) {
                    this.importanceField = value;
                    this.RaisePropertyChanged("importance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lat {
            get {
                return this.latField;
            }
            set {
                if ((object.ReferenceEquals(this.latField, value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string licence {
            get {
                return this.licenceField;
            }
            set {
                if ((object.ReferenceEquals(this.licenceField, value) != true)) {
                    this.licenceField = value;
                    this.RaisePropertyChanged("licence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lon {
            get {
                return this.lonField;
            }
            set {
                if ((object.ReferenceEquals(this.lonField, value) != true)) {
                    this.lonField = value;
                    this.RaisePropertyChanged("lon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long osm_id {
            get {
                return this.osm_idField;
            }
            set {
                if ((this.osm_idField.Equals(value) != true)) {
                    this.osm_idField = value;
                    this.RaisePropertyChanged("osm_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string osm_type {
            get {
                return this.osm_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.osm_typeField, value) != true)) {
                    this.osm_typeField = value;
                    this.RaisePropertyChanged("osm_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long place_id {
            get {
                return this.place_idField;
            }
            set {
                if ((this.place_idField.Equals(value) != true)) {
                    this.place_idField = value;
                    this.RaisePropertyChanged("place_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long place_rank {
            get {
                return this.place_rankField;
            }
            set {
                if ((this.place_rankField.Equals(value) != true)) {
                    this.place_rankField = value;
                    this.RaisePropertyChanged("place_rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Route", Namespace="http://schemas.datacontract.org/2004/07/Proxy_WCF")]
    [System.SerializableAttribute()]
    public partial class Route : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAP_WCF.ProxyServices.Hints hintsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAP_WCF.ProxyServices.Info infoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAP_WCF.ProxyServices.Path[] pathsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAP_WCF.ProxyServices.Hints hints {
            get {
                return this.hintsField;
            }
            set {
                if ((object.ReferenceEquals(this.hintsField, value) != true)) {
                    this.hintsField = value;
                    this.RaisePropertyChanged("hints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAP_WCF.ProxyServices.Info info {
            get {
                return this.infoField;
            }
            set {
                if ((object.ReferenceEquals(this.infoField, value) != true)) {
                    this.infoField = value;
                    this.RaisePropertyChanged("info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAP_WCF.ProxyServices.Path[] paths {
            get {
                return this.pathsField;
            }
            set {
                if ((object.ReferenceEquals(this.pathsField, value) != true)) {
                    this.pathsField = value;
                    this.RaisePropertyChanged("paths");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hints", Namespace="http://schemas.datacontract.org/2004/07/Proxy_WCF")]
    [System.SerializableAttribute()]
    public partial class Hints : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double visited_nodesaverageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long visited_nodessumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double visited_nodesaverage {
            get {
                return this.visited_nodesaverageField;
            }
            set {
                if ((this.visited_nodesaverageField.Equals(value) != true)) {
                    this.visited_nodesaverageField = value;
                    this.RaisePropertyChanged("visited_nodesaverage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long visited_nodessum {
            get {
                return this.visited_nodessumField;
            }
            set {
                if ((this.visited_nodessumField.Equals(value) != true)) {
                    this.visited_nodessumField = value;
                    this.RaisePropertyChanged("visited_nodessum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Info", Namespace="http://schemas.datacontract.org/2004/07/Proxy_WCF")]
    [System.SerializableAttribute()]
    public partial class Info : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] copyrightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long tookField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] copyrights {
            get {
                return this.copyrightsField;
            }
            set {
                if ((object.ReferenceEquals(this.copyrightsField, value) != true)) {
                    this.copyrightsField = value;
                    this.RaisePropertyChanged("copyrights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long took {
            get {
                return this.tookField;
            }
            set {
                if ((this.tookField.Equals(value) != true)) {
                    this.tookField = value;
                    this.RaisePropertyChanged("took");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Path", Namespace="http://schemas.datacontract.org/2004/07/Proxy_WCF")]
    [System.SerializableAttribute()]
    public partial class Path : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ascendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] bboxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double descendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double distanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAP_WCF.ProxyServices.Instruction[] instructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAP_WCF.ProxyServices.Points pointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long transfersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double weightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ascend {
            get {
                return this.ascendField;
            }
            set {
                if ((this.ascendField.Equals(value) != true)) {
                    this.ascendField = value;
                    this.RaisePropertyChanged("ascend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] bbox {
            get {
                return this.bboxField;
            }
            set {
                if ((object.ReferenceEquals(this.bboxField, value) != true)) {
                    this.bboxField = value;
                    this.RaisePropertyChanged("bbox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double descend {
            get {
                return this.descendField;
            }
            set {
                if ((this.descendField.Equals(value) != true)) {
                    this.descendField = value;
                    this.RaisePropertyChanged("descend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                if ((this.distanceField.Equals(value) != true)) {
                    this.distanceField = value;
                    this.RaisePropertyChanged("distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAP_WCF.ProxyServices.Instruction[] instructions {
            get {
                return this.instructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.instructionsField, value) != true)) {
                    this.instructionsField = value;
                    this.RaisePropertyChanged("instructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAP_WCF.ProxyServices.Points points {
            get {
                return this.pointsField;
            }
            set {
                if ((object.ReferenceEquals(this.pointsField, value) != true)) {
                    this.pointsField = value;
                    this.RaisePropertyChanged("points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long transfers {
            get {
                return this.transfersField;
            }
            set {
                if ((this.transfersField.Equals(value) != true)) {
                    this.transfersField = value;
                    this.RaisePropertyChanged("transfers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double weight {
            get {
                return this.weightField;
            }
            set {
                if ((this.weightField.Equals(value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Points", Namespace="http://schemas.datacontract.org/2004/07/Proxy_WCF")]
    [System.SerializableAttribute()]
    public partial class Points : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[][] coordinatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                if ((object.ReferenceEquals(this.coordinatesField, value) != true)) {
                    this.coordinatesField = value;
                    this.RaisePropertyChanged("coordinates");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Instruction", Namespace="http://schemas.datacontract.org/2004/07/Proxy_WCF")]
    [System.SerializableAttribute()]
    public partial class Instruction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double distanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long exit_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool exitedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double headingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] intervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double last_headingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long signField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string street_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string street_refField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double turn_angleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                if ((this.distanceField.Equals(value) != true)) {
                    this.distanceField = value;
                    this.RaisePropertyChanged("distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long exit_number {
            get {
                return this.exit_numberField;
            }
            set {
                if ((this.exit_numberField.Equals(value) != true)) {
                    this.exit_numberField = value;
                    this.RaisePropertyChanged("exit_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool exited {
            get {
                return this.exitedField;
            }
            set {
                if ((this.exitedField.Equals(value) != true)) {
                    this.exitedField = value;
                    this.RaisePropertyChanged("exited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double heading {
            get {
                return this.headingField;
            }
            set {
                if ((this.headingField.Equals(value) != true)) {
                    this.headingField = value;
                    this.RaisePropertyChanged("heading");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] interval {
            get {
                return this.intervalField;
            }
            set {
                if ((object.ReferenceEquals(this.intervalField, value) != true)) {
                    this.intervalField = value;
                    this.RaisePropertyChanged("interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double last_heading {
            get {
                return this.last_headingField;
            }
            set {
                if ((this.last_headingField.Equals(value) != true)) {
                    this.last_headingField = value;
                    this.RaisePropertyChanged("last_heading");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long sign {
            get {
                return this.signField;
            }
            set {
                if ((this.signField.Equals(value) != true)) {
                    this.signField = value;
                    this.RaisePropertyChanged("sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street_name {
            get {
                return this.street_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.street_nameField, value) != true)) {
                    this.street_nameField = value;
                    this.RaisePropertyChanged("street_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street_ref {
            get {
                return this.street_refField;
            }
            set {
                if ((object.ReferenceEquals(this.street_refField, value) != true)) {
                    this.street_refField = value;
                    this.RaisePropertyChanged("street_ref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double turn_angle {
            get {
                return this.turn_angleField;
            }
            set {
                if ((this.turn_angleField.Equals(value) != true)) {
                    this.turn_angleField = value;
                    this.RaisePropertyChanged("turn_angle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyServices.IJCDecauxAPI")]
    public interface IJCDecauxAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxAPI/Contracts", ReplyAction="http://tempuri.org/IJCDecauxAPI/ContractsResponse")]
        SOAP_WCF.ProxyServices.Contract[] Contracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxAPI/Contracts", ReplyAction="http://tempuri.org/IJCDecauxAPI/ContractsResponse")]
        System.Threading.Tasks.Task<SOAP_WCF.ProxyServices.Contract[]> ContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxAPI/Stations", ReplyAction="http://tempuri.org/IJCDecauxAPI/StationsResponse")]
        SOAP_WCF.ProxyServices.Station[] Stations(string contractName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxAPI/Stations", ReplyAction="http://tempuri.org/IJCDecauxAPI/StationsResponse")]
        System.Threading.Tasks.Task<SOAP_WCF.ProxyServices.Station[]> StationsAsync(string contractName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJCDecauxAPIChannel : SOAP_WCF.ProxyServices.IJCDecauxAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JCDecauxAPIClient : System.ServiceModel.ClientBase<SOAP_WCF.ProxyServices.IJCDecauxAPI>, SOAP_WCF.ProxyServices.IJCDecauxAPI {
        
        public JCDecauxAPIClient() {
        }
        
        public JCDecauxAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JCDecauxAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAP_WCF.ProxyServices.Contract[] Contracts() {
            return base.Channel.Contracts();
        }
        
        public System.Threading.Tasks.Task<SOAP_WCF.ProxyServices.Contract[]> ContractsAsync() {
            return base.Channel.ContractsAsync();
        }
        
        public SOAP_WCF.ProxyServices.Station[] Stations(string contractName) {
            return base.Channel.Stations(contractName);
        }
        
        public System.Threading.Tasks.Task<SOAP_WCF.ProxyServices.Station[]> StationsAsync(string contractName) {
            return base.Channel.StationsAsync(contractName);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyServices.IOpenStreetMapAPI")]
    public interface IOpenStreetMapAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenStreetMapAPI/Querry", ReplyAction="http://tempuri.org/IOpenStreetMapAPI/QuerryResponse")]
        SOAP_WCF.ProxyServices.Place[] Querry([System.ServiceModel.MessageParameterAttribute(Name="querry")] string querry1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenStreetMapAPI/Querry", ReplyAction="http://tempuri.org/IOpenStreetMapAPI/QuerryResponse")]
        System.Threading.Tasks.Task<SOAP_WCF.ProxyServices.Place[]> QuerryAsync(string querry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenStreetMapAPI/GeoCoordinate", ReplyAction="http://tempuri.org/IOpenStreetMapAPI/GeoCoordinateResponse")]
        System.Device.Location.GeoCoordinate GeoCoordinate(string querry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenStreetMapAPI/GeoCoordinate", ReplyAction="http://tempuri.org/IOpenStreetMapAPI/GeoCoordinateResponse")]
        System.Threading.Tasks.Task<System.Device.Location.GeoCoordinate> GeoCoordinateAsync(string querry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenStreetMapAPI/Route", ReplyAction="http://tempuri.org/IOpenStreetMapAPI/RouteResponse")]
        SOAP_WCF.ProxyServices.Route Route(System.Device.Location.GeoCoordinate start, System.Device.Location.GeoCoordinate end, string transport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpenStreetMapAPI/Route", ReplyAction="http://tempuri.org/IOpenStreetMapAPI/RouteResponse")]
        System.Threading.Tasks.Task<SOAP_WCF.ProxyServices.Route> RouteAsync(System.Device.Location.GeoCoordinate start, System.Device.Location.GeoCoordinate end, string transport);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOpenStreetMapAPIChannel : SOAP_WCF.ProxyServices.IOpenStreetMapAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OpenStreetMapAPIClient : System.ServiceModel.ClientBase<SOAP_WCF.ProxyServices.IOpenStreetMapAPI>, SOAP_WCF.ProxyServices.IOpenStreetMapAPI {
        
        public OpenStreetMapAPIClient() {
        }
        
        public OpenStreetMapAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OpenStreetMapAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenStreetMapAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenStreetMapAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAP_WCF.ProxyServices.Place[] Querry(string querry1) {
            return base.Channel.Querry(querry1);
        }
        
        public System.Threading.Tasks.Task<SOAP_WCF.ProxyServices.Place[]> QuerryAsync(string querry) {
            return base.Channel.QuerryAsync(querry);
        }
        
        public System.Device.Location.GeoCoordinate GeoCoordinate(string querry) {
            return base.Channel.GeoCoordinate(querry);
        }
        
        public System.Threading.Tasks.Task<System.Device.Location.GeoCoordinate> GeoCoordinateAsync(string querry) {
            return base.Channel.GeoCoordinateAsync(querry);
        }
        
        public SOAP_WCF.ProxyServices.Route Route(System.Device.Location.GeoCoordinate start, System.Device.Location.GeoCoordinate end, string transport) {
            return base.Channel.Route(start, end, transport);
        }
        
        public System.Threading.Tasks.Task<SOAP_WCF.ProxyServices.Route> RouteAsync(System.Device.Location.GeoCoordinate start, System.Device.Location.GeoCoordinate end, string transport) {
            return base.Channel.RouteAsync(start, end, transport);
        }
    }
}
